apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - image: lholmquist/this-will-be-replaced:latest
          imagePullPolicy: Always
          name: ui
          ports:
            - containerPort: 8080
              protocol: TCP
